# Site settings
name: Gajendra Kumar
email: raaz2.gajendra@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "java, Spring framework, Spring-boot, Reactor – reactive programming, Jpa, Hibernate, Spring WebFlux, Web Services, REST, Spring security, Apache Camel. JMS- activemq, JavaScript, jquery, jquery plugins, Bootstrap 2 and 3, angular-1"
skills: "Senior Software Engineer"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/gajendra-kumar-1b368870/
  - title: stackoverflow
    url: https://stackoverflow.com/users/5470839/gajendra-kumar
  - title: github
    url: https://github.com/codecracker2014
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
